### PR TITLE
Added alert for mon quorum at risk

### PR DESCRIPTION
**Pull request by shtripat**
ceph-mixins-bug-id: ceph/ceph-mixins/issues/10
Signed-off-by: Shubhendu <shtripat@redhat.com>

### CODE REVIEW

**Comment by shtripat** [comment]
@pcuzner @b-ranto please review

**Comment by b-ranto** [comment]
If this works then it would be great but I am afraid `ceph-mgr` might stop reporting the data once the monitors can't reach the quorum. :-/

It is worth testing this though.

**Comment by shtripat** [comment]
>> It is worth testing this though.

Let me test and verify this.

**Comment by pcuzner** [comment]
Agree with @b-ranto 
The alert as it stands says 'a mon is not in quorum' not that cluster quorum is lost - and the challenge is that when you do lose quorum, mgr will not be able to connect, which means prom metrics are now longer received by the scrape job.

As an alternative, could we alert if the mons in quorum reaches 2. Having only 2 active would then be the trigger for the admin to do something? Also is 5mins a good time for tie in with rook mon recovery actions, or should it be higher?

**Comment by shtripat** [comment]
> Agree with @b-ranto
> The alert as it stands says 'a mon is not in quorum' not that cluster quorum is lost - and the challenge is that when you do lose quorum, mgr will not be able to connect, which means prom metrics are now longer received by the scrape job.
> 
> As an alternative, could we alert if the mons in quorum reaches 2. Having only 2 active would then be the trigger for the admin to do something? Also is 5mins a good time for tie in with rook mon recovery actions, or should it be higher?

Ack. Will change the logic to check if mon in quorum is less than 3. Also the time I will set as 15mins by default.

**Review by umangachapagain — APPROVED** [review]

**Pull request merged**
